# Generated by Django 4.2.6 on 2023-10-10 11:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.EmailField(max_length=35)),
                ('password', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
