# Generated by Django 4.2.6 on 2023-10-11 05:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=35)),
                ('password', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'Login',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
