# Generated by Django 4.2.6 on 2023-10-11 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
